## This Prometheus YAML for ec2_sd_configs


scrape_configs:
  - job_name: "PS-EC2_Sd"
    ec2_sd_configs:
      - access_key: XYZ
        secret_key: ABCDEF
        region: ap-south-1

    relabel_configs:
      - source_labels: [__meta_ec2_public_ip]
        regex: "(.*)"
        replacement: "${1}:9100"
        target_label: __address__
